# Generated by Django 4.2 on 2023-05-09 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_address_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
