# Generated by Django 4.2 on 2023-05-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last',
        ),
    ]
