# Generated by Django 4.2 on 2023-05-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_post_content_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cnt_people',
            field=models.ImageField(default=2, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='price_deliver',
            field=models.FloatField(default=0),
        ),
    ]
