# Generated by Django 4.2 on 2023-05-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_cnt_people_post_price_post_price_deliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cnt_people',
            field=models.IntegerField(default=2),
        ),
    ]
