# Generated by Django 4.2 on 2023-05-05 22:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_date_deliver_post_time_deliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cnt_people',
            field=models.IntegerField(default=2, verbose_name='Количество людей'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_deliver',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата ордера'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.FloatField(default=0, verbose_name='Стоимость всей еды'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price_deliver',
            field=models.FloatField(default=0, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_deliver',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время ордера'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Название ордера'),
        ),
    ]
