# Generated by Django 4.2 on 2023-05-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_post_cnt_people_alter_post_date_deliver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_deliver',
            field=models.TimeField(default='13:00:00', verbose_name='Время ордера'),
        ),
    ]
