# Generated by Django 4.2 on 2023-05-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_post_time_deliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_deliver',
            field=models.TimeField(default='17:30:00', verbose_name='Время ордера'),
        ),
    ]
