# Generated by Django 4.2 on 2023-05-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_post_time_deliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='post_pics/', verbose_name='Фотография'),
        ),
    ]
