# Generated by Django 4.2 on 2023-05-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_post_options_alter_post_cnt_people_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mod',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Мод ордера'),
        ),
    ]
